image: node:8

services:
  - postgres

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: cgawsbrokerprodgq3wrvn8c8a772q
  POSTGRES_USER: utz6kah1zq8t2nyg
  POSTGRES_PASSWORD: of2fbobp423i89ztu7g7d136h


stages:
  # - build
  - test

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

#install_dependencies:
#  stage: build
#  script:
#    - npm install
#  artifacts:
#    paths:
#      - node_modules/

connect:
  image: postgres
  stage: test
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -D "$POSTGRES_DB" < srt-database.sql

test_with_lab:
  stage: test
  coverage: '/All files[^0-9]*\d+\.\d+/'
  artifacts:
    paths:
      - coverage/
  script:
    - npm install
    - export NODE_ENV=sqlite
    - npm test